baseURL = 'https://corretorpaulobaptista.com.br/'
languageCode = 'pt-br'
title = 'Paulo Baptista Corretor Imobiliário'
theme = "ananke"

[params.contact]
image = "/uploads/paulo-baptista.png"  # Caminho da imagem do corretor
name = "Paulo Baptista"
email = "paulobaptista9@gmail.com"
phone = "(11) 98185-2310"

[params.about]
name = "Paulo Baptista"
role = "Corretor Imobiliário"
experience = "5"
description = "Consultor Imobiliário especialista, sou responsável por encontrar o seu imóvel ideal, seja para moradia quanto para investimento, aliado a melhor oportunidade de negócio."
whatsapp = "(11) 981852310"
image = "/uploads/paulo-baptista.png"

paginate = 6
paginateSecond = 9

[params]
  CorretorNome = "Paulo Baptista"

  [[params.Diferenciais]]
    Title = "Atendimento Personalizado"
    Description = "Paulo acompanha cada etapa da compra, entendendo suas necessidades e oferecendo as melhores opções para você."
    Icon = "uploads/atendimento.png"

  [[params.Diferenciais]]
    Title = "Oportunidades Exclusivas"
    Description = "Acesso a imóveis com condições diferenciadas e negociações diretas para garantir o melhor investimento."
    Icon = "uploads/oportunidades.png"

  [[params.Diferenciais]]
    Title = "Segurança e Transparência"
    Description = "Todo o processo de compra com suporte completo, garantindo tranquilidade e segurança jurídica para você."
    Icon = "uploads/seguranca.png"